### PR TITLE
fix(android): set initial page natively

### LINKED ISSUE #400: initial page render question
## Ask your Question

when PagerView rendered, 
even though the initialPage={1} is selected, Page 0 is displayed first then Page 1 is displayed.
i use Android simulator. help!

### PR DESCRIPTION
**Pull request by mikeqcp**
# Summary

Closes #400

On Android, setting initial page was implemented asynchronously on React side and native `onPageSelected` was fired twice (with default value and then with proper one).
This PR moves the implementation directly to `ViewPager2` API.

### What's required for testing (prerequisites)?

Setup `Basic Example` with `initialPage={1}` and with `onPageSelected={(e: any) => console.log(e.nativeEvent.position)}`

### What are the steps to reproduce (after prerequisites)?

Open the Example and see what pages are reported in `onPageSelected` callback

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)

### CODE REVIEW

File: android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt [hunk 1]
```diff
@@ -139,6 +145,13 @@ class PagerViewViewManager : ViewGroupManager<ViewPager2>() {
     viewPager.isUserInputEnabled = value
   }
 
+  @ReactProp(name = "initialPage", defaultInt = 0)
+  fun setInitialPage(viewPager: ViewPager2, value: Int) {
+    viewPager.post {
```
Comment (mikeqcp) [inline android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt:150]: It needs to be set within `post` because `ViewPager2` has an issue and initial page doesnt change unless this call is defered to the next cycle
more details here: https://stackoverflow.com/questions/56311862/viewpager2-default-position

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v5.3.3
