### PR TITLE
fix(ios): resolve scrollEnabled prop initialization timing issue

### LINKED ISSUE #1029: scrollEnabled={false} doesn't prevent swipe on iOS
## Environment

- **React Native version**: 0.81.4
- **react-native-pager-view version**: 6.9.1
- **Platform**: iOS
- **iOS version**: 26.x (tested on simulator/device)
- **macOS version**: 26.0 (Sequoia)
- **Xcode version**: 26.0.1
- **Expo SDK version**: ~54.0.10
- **Architecture**: New Architecture enabled

## Description

The `scrollEnabled={false}` prop does not prevent user swipe gestures on iOS. Despite setting this prop to `false`, users can still swipe horizontally to change pages in the PagerView component.

**Expected behavior**: When `scrollEnabled={false}` is set, users should not be able to swipe between pages. Page changes should only be possible programmatically via `setPage()`.

**Actual behavior**: Users can still swipe between pages even with `scrollEnabled={false}`. The prop seems to be ignored on iOS.

**Note**: This appears to work correctly on Android.

## Reproducible Demo

```tsx
import React, { useEffect, useRef, useState } from 'react';
import { View, Text, Button, StyleSheet } from 'react-native';
import PagerView from 'react-native-pager-view';

export default function App() {
  return (
    <View style={styles.container}>
      <PagerView
        style={styles.pager}
        initialPage={0}
        scrollEnabled={false}  // This should prevent swiping but doesn't work on iOS
      >
        <View key="1" style={[styles.page, { backgroundColor: '#FF6B6B' }]}>
          <Text style={styles.text}>Page 1</Text>
        </View>
        
        <View key="2" style={[styles.page, { backgroundColor: '#4ECDC4' }]}>
          <Text style={styles.text}>Page 2</Text>
        </View>
        
        <View key="3" style={[styles.page, { backgroundColor: '#45B7D1' }]}>
          <Text style={styles.text}>Page 3</Text>
        </View>
      </PagerView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  pager: {
    flex: 1,
  },
  page: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text: {
    fontSize: 24,
    fontWeight: 'bold',
    color: 'white',
  },
});
```

**Steps to reproduce**:
1. Create a new React Native project with the environment specified above
2. Install `react-native-pager-view@6.9.1`
3. Copy the code above into your App component
4. Run on iOS simulator or device
5. Try to swipe between pages - swiping works even though `scrollEnabled={false}`
6. Compare with Android where the prop works correctly

**Additional context**: 
I'm using this in a multi-step form where I want to control navigation programmatically with "Next" and "Previous" buttons only, without allowing users to swipe between steps.

### PR DESCRIPTION
**Pull request by okwasniewski**
# Summary

Store scrollEnabled state in an ivar and apply it when the scroll view becomes available, rather than attempting to set it before initialization. This ensures the prop works reliably regardless of when props are updated relative to UIPageViewController setup.

Fixes #1029

## Test Plan

Check if scroll enabled works correctly. 

---

> [!NOTE]
> Store `scrollEnabled` in an ivar and apply it once the inner `UIScrollView` exists, updating consistently on prop/imperative changes and lifecycle resets.
> 
> - **iOS PagerView (`RNCPagerViewComponentView`)**:
>   - Store `scrollEnabled` in `_scrollEnabled` with default `YES`; reset on recycle.
>   - Add `applyScrollEnabled` and call it after `UIPageViewController` setup, on prop changes, and in imperative setter.
>   - Update `updateProps` to compare old/new `scrollEnabled`, set `_scrollEnabled`, then apply.
>   - Replace direct `scrollView.scrollEnabled` writes with deferred application via `_scrollEnabled`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit db0029e52d48fcef4e9fd69e03f902f7ece4d094. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: ios/RNCPagerViewComponentView.mm [hunk 1]
```diff
@@ -143,6 +148,12 @@ - (void)shouldDismissKeyboard:(RNCViewPagerKeyboardDismissMode)dismissKeyboard {
 #endif
 }
 
+- (void)applyScrollEnabled {
```
[the remark this answers is not in the document]
Comment (okwasniewski) [reply ios/RNCPagerViewComponentView.mm]: fixed

File: ios/RNCPagerViewComponentView.mm [hunk 2]
```diff
@@ -76,6 +80,7 @@ - (instancetype)initWithFrame:(CGRect)frame
         _destinationIndex = -1;
         _layoutDirection = @"ltr";
         _overdrag = NO;
+        _scrollEnabled = YES;
```
Comment (johankasperi) [inline ios/RNCPagerViewComponentView.mm]: When adopting this code to patch version 6.9.1 in our app I had to remove this line to make it work. Don't know if you need to do the same in this PR but just wanted to share my findings and give you a heads up. Thank you for fixing this!

Comment (okwasniewski) [reply ios/RNCPagerViewComponentView.mm]: Thanks for checking it out! I'm not sure why it wouldn't work for you.. Without setting this to YES the state will be desynchronized (as the default for a scroll view is to have scroll enabled). 

I did some additional tests and it was working well with this.
