### PR TITLE
fix(#722): revert not working back navigation gesture in favour of PagerView inside ScrollView

### LINKED ISSUE #722: 6.2.0 breaks vertical scrolling of ScrollView parent
## Environment

"react-native": "0.71.6",
"react-native-pager-view": "6.2.0",
"react-native-tab-view": "^3.5.1",

## Description

I was trying to render `TabView` of react-native-tab-view inside of a `ScrollView`, but after upgrading to v6.2.0 for pager-view, the vertical scrolling of the scroll view would lock and only adjust if I didn't select the element that was being rendered as a child under the `render()` function of the PagerViewAdapter; so if I tried scrolling when selecting a `TabBar` it would scroll correctly - if I switched out the `render(<SceneView/>)` for a generic `View` I could scroll fine.

Inside react-native-tab-view/src/TabView:

```
return (
  <React.Fragment>
    {tabBarPosition === 'top' &&
      renderTabBar({
        ...sceneRendererProps,
        navigationState,
      })}
    {render(
      navigationState.routes.map((route, i) => {
        return (
          <SceneView
            {...sceneRendererProps}
            addEnterListener={addEnterListener}
            key={route.key}
            index={i}
            lazy={typeof lazy === 'function' ? lazy({ route }) : lazy}
            lazyPreloadDistance={lazyPreloadDistance}
            navigationState={navigationState}
            style={sceneContainerStyle}
          >
            {({ loading }) =>
              loading
                ? renderLazyPlaceholder({ route })
                : renderScene({
                    ...sceneRendererProps,
                    route,
                  })
            }
          </SceneView>
        );
      })
    )}
    {tabBarPosition === 'bottom' &&
      renderTabBar({
        ...sceneRendererProps,
        navigationState,
      })}
  </React.Fragment>
);
```

This PagerView adapter inherits `PagerViewProps` props from react-native-pager-view and after downgrading the library (to "react-native-pager-view": "6.1.4"), the entire page can scroll fine again, I was originally going to pin the bug on react-native-tab-view but it seems that this issue has happened with other components that depend on the library (see: https://github.com/callstack/react-native-pager-view/issues/713)

## Reproducible Demo

When you use the following code and try to scroll vertically on any elements rendered inside of `_renderTab` nothing will happen. If you downgrade react-native-pager-view to 6.1.4 it will work.

```
import React, {Component} from 'react';
import {TabBar, TabView} from 'react-native-tab-view';

_renderTab = (tab) => {
  return (
    <View>{...some stuff to render}</View>
  )
}

_renderTabBar = (props) => {
  return (
    <TabBar
      {...props}
      renderLabel={({route}) => (
        <View>
          <Text style={styles.textStyles}>{route.title}</Text>
        </View>
      )}
    />
  );
};

_renderScene = ({route, jumpTo}) => {
    switch (route.key) {
      case 'day':
        return this._renderTab("day");
      case 'week':
        return this._renderTab("week");
      case 'month':
        return this._renderTab("month");
    }
};

render() {
  return (
    <ScrollView
      contentContainerStyle={{flexGrow: 1}}
      nestedScrollEnabled={true}
      scrollEnabled={true}>
      <View>
        <TabView
          navigationState={this.state}
          onIndexChange={(index) => {
            this.setState({index});
          }}
          renderScene={this._renderScene}
          renderTabBar={this._renderTabBar}
        />
      </View>
    </ScrollView>
  )
}
```

### PR DESCRIPTION
**Pull request by MateWW**
# Summary

#### Issue
Currently scroll over legacy pager view is not working while nested inside scroll view.
Nesting might be necessary while we have big header which you don't want to be visible while you are swiping pages.

#### Root cause
The issue arise with [6.2.0 version](https://github.com/callstack/react-native-pager-view/commit/769a3a21500fbe40c1909c9bf50f724c76a5b435#diff-b76afe0b22639c5e44b27b49c147284272978b94c8975b572b7a10cf8a3f5ba6R18) and support for navigate back gesture.

#### Solution
I've tested that navigate back gesture and it didn't worked for me as you may see on attached video.
I've also checked if basic react native ScrollView supports that for horizontal mode and it's not.
Based on all above I believe it's not worth to block users and I reverted that change.
I think we can revisit that use case later and fix that long living regression.

## Test Plan

| Architecture      | Before | After |
| ------- | :---------: | :---------: |
| Fabric     | <video src="https://github.com/user-attachments/assets/1051e996-402e-4cd9-a127-e7e475dba504"> | <video src="https://github.com/user-attachments/assets/17a54789-95fa-4ee2-8d42-4266cdba479c">  | 
| Paper |  <video src="https://github.com/user-attachments/assets/98e75c77-8268-4c5d-b3c3-baaad275ddce"> | <video src="https://github.com/user-attachments/assets/2b07c896-5490-4b66-af80-0dddf56bf91d"> |

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅    |
| Android |    ❌     |

## Checklist

- [x] I have tested this on a device and a simulator

### CODE REVIEW

**Comment by MrRefactor** [comment]
This PR will be merged once we close this one: https://github.com/callstack/react-native-pager-view/pull/918

File: example/src/tabView/NestedTabViewExample.tsx [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+    <ScrollView
+      contentContainerStyle={{flexGrow: 1, backgroundColor: 'red'}}
+      nestedScrollEnabled={false}
+      scrollEnabled={true}
+    >
+      <Header />
+
+      <View>
+        <TabView
+          // TODO: Fix the height measurement for nested pager view
```
Comment (MrRefactor) [inline example/src/tabView/NestedTabViewExample.tsx:46]: Please remove that TODO

**Review by MrRefactor — APPROVED** [review]

**Comment by MateWW** [comment]
> @MateWW Could you check this PR https://github.com/callstack/react-native-pager-view/pull/771/files if this is the same thing?

yup, just in my case we have additional example in app to test that scenario

**Comment by troZee** [comment]
> > @MateWW Could you check this PR https://github.com/callstack/react-native-pager-view/pull/771/files if this is the same thing?
> 
> yup, just in my case we have additional example in app to test that scenario

Thank you 🙏 we will check that change once we test other PRs, which are already in a queue
